name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Bofire
        run: pip install .[testing]
      - name: Run tests
        run: |
        conda install -c conda-forge cyipopt
        pytest -ra --cov=bofire --cov-report term-missing tests
      #- name: Upload coverage
      #  run: bash <(curl -s https://codecov.io/bash)
          
