name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Bofire
        run: pip install .[testing]
      - name: Install optional dependencies
        run: conda install -c conda-forge cyipopt
      - name: Run tests
        run: pytest -ra --cov=bofire --cov-report term-missing tests
          
